export const menu = [
    {
        id: 1,
        title: 'egg toast',
        category: 'breakfast',
        price: 6.99,
        img:'./images/my-1.jpg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
    {
        id: 2,
        title: 'pasta',
        category: 'lunch',
        price: 15.99,
        img:'./images/my-2.jpg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
    {
        id: 3,
        title: 'Sirloin Steak',
        category: 'dinner',
        price: 23.99,
        img:'./images/my-3.jpg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
    {
        id: 4,
        title: 'eggs',
        category: 'dessert',
        price: 13.59,
        img:'./images/item-1.jpeg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
    {
        id: 5,
        title: 'lunch',
        category: 'lunch',
        price: 15.99,
        img:'./images/item-2.jpeg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
    {
        id: 6,
        title: 'g',
        category: 'shakes',
        price: 16.99,
        img:'./images/item-3.jpeg',
        remote_img:'',
        desc:'Lorem ipsum dolor sit amet consectetur adipi sicing elit. Obcaecatipossimus excepturi. Illo voluptate amet distinctio cum, tempore iure magni nam aliquam',
    },
]